version: "3.8"

services:
    test_parser_db:
        image: mysql
        container_name: test_parser_db
        environment:
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        ports:
          - '5105:3306'
    django_test_parser:
        build: .
        container_name: django_test_parser
        command: > 
            sh -c "python manage.py collectstatic --noinput &&
                   python manage.py makemigrations api &&
                   python manage.py migrate &&
                   python manage.py create_super_user &&
                   python manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/usr/src/app
        ports: 
            - "8000:8000"
        depends_on:
            - start_bot
            - test_parser_db
            - test_parser_redis
    test_parser_redis:  
        image: redis
        container_name: test_parser_redis
        ports:
        - "6379"
        restart: always
    celery:
        build: .
        command: celery -A test_parser worker -l INFO
        volumes:
            - .:/usr/src/app
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=redis://test_parser_redis:6379/0
            - CELERY_BACKEND=redis://test_parser_redis:6379/0
        depends_on:
            - django_test_parser
            - test_parser_redis
    chrome:
        image: selenium/standalone-chrome:latest
        shm_size: 8g
        restart: always
        hostname: chrome
    start_bot:
        build: .
        volumes:
            - .:/usr/src/app
        command: sh -c "sleep 10 && python manage.py bot_setup"

        
